[build]
  publish = "dist" # Replace "dist" with the folder containing your `.html` files if different.
  command = "npm run build" # Use this only if you're using a build tool like Tailwind CLI.

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
